# Here you can specify default options for TinyMCE across all controllers
#
theme: advanced
theme_advanced_buttons1: bold,italic,underline,strikethrough, bullist,numlist,undo,redo
theme_advanced_buttons2: ''
theme_advanced_buttons3: ''
theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
content_css: public/stylesheets/custom_content.css
#My complete tinymce call (or whatever):
#    mode : "textareas",
#    theme : "advanced",
#    width : "245",
#    height : "150",
#    theme_advanced_buttons1 : "bold,italic,underline,strikethrough, bullist,numlist,undo,redo",
#    theme_advanced_buttons2 : "",
#    theme_advanced_buttons3 : "",
#    theme_advanced_toolbar_location : "external",
#    theme_advanced_toolbar_align : "bottom",
#    theme_advanced_statusbar : false,
#    theme_advanced_resizing : false
#plugins:
#  - table
#  - fullscreen
